# fly.toml app configuration file generated for dresser-llm-proxy
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dresser-llm-proxy"
primary_region = "iad"

[build]

[env]
  NODE_ENV = "production"

[http_service]
  internal_port = 8787
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256