app = "dresser-llm-proxy"
primary_region = "iad"

[build]

[env]
  PORT = "8787"
  HOST = "0.0.0.0"

[http_service]
  internal_port = 8787
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[deploy]
  release_command = "echo 'LLM Proxy deployed successfully'"
